### ISSUE TITLE
Not support Parsedown 1.7.3

### ISSUE THREAD

**Issue by drify** [BenjaminHoegh/ParsedownMath#1]
I tried to use this extension with Parsedown 1.7.3 and it failed drastically... Every line with Math begins with `<>`, which makes no sense.

Your code suggests that it is compatible with Parsedown 1.7.1+, but please check again.

**Comment by SwithFr** [comment]
Any updates ?

**Comment by BenjaminHoegh** [comment]
I'm so sorry! I totally forgot about this, I'm taking a look into now
