### ISSUE TITLE
Hope to support the in-line formula of $ ...... $

### ISSUE THREAD

**Issue by MatrixCoder-Chen** [BenjaminHoegh/ParsedownMath#2]
希望支持$ ... $的行内公式

**Comment by BenjaminHoegh** [comment]
Please write in English

**Comment by MatrixCoder-Chen** [comment]
Hope to support the in-line formula of ```$ ...... $```

**Comment by fardina** [comment]
Hi @BenjaminHoegh Thank you for your great work. I also need inline math `$...$`. Is it possible to make ParsedownMath  support this?

**Comment by BenjaminHoegh** [comment]
You takling about inline `$...$` or `$$...$$` ? Can’t recommend single

**Comment by fardina** [comment]
I need `$...` for inline and `$$...$$`for block.

**Comment by fardina** [comment]
@BenjaminHoegh Any progress on this?

**Comment by BenjaminHoegh** [comment]
> @BenjaminHoegh Any progress on this?

No sorry, i have been way to busy helping organize my brothers wedding but I can look into it on Saturday, should be able to make a a fix for it in a few minutes if everything works 👌

**Comment by BenjaminHoegh** [comment]
@fardina do you have any examples where single dollar fails?

**Comment by fardina** [comment]
@BenjaminHoegh Yes. Here is an example that ParsedownMath does not protect math:

```
If decomposition of $n$ is like $n=p_{1}^{ \alpha _{1}}p_{2}^{ \alpha _{2}}...p_{k}^{ \alpha _{k}}$ where $p_{1},p_{2},...,p_{k}$ are prime numbers and $ \alpha _{1}, \alpha _{2},..., \alpha _{k}$ are naturals:
$$ \varphi (n)=n(1-\frac{1}{p_{1}})(1-\frac{1}{p_{2}})...(1-\frac{1}{p_{k}})$$
```
Here is how it looks like:
![false](https://user-images.githubusercontent.com/13521621/84571391-13694b00-ada8-11ea-8652-72716f00f173.png)

and here is how it should be:
![correct](https://user-images.githubusercontent.com/13521621/84571434-54615f80-ada8-11ea-8516-278e713a48ce.png)
